[profile.default]
src = "src"
test = "test/foundry/v0.8"
out = "out"
cache_path = 'cache-foundry'
libs = ['node_modules', "lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
