name: "Enhancement Report"
description: "Suggest an improvement to an existing feature"
labels: [enhance]
body:
  - type: textarea
    id: request
    attributes:
      label: Improvement Suggestion
      description: A clear and concise description of what the motivation or the current problem is and what is the suggested improvement?
    validations:
      required: true