#!/usr/bin/env bash

if [ -z "$(git status --porcelain)" ]; then
  echo "PASSED: Working directory clean"
else
  echo "FAILED: Working directory not clean."
  exit 1
fi

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd .. && pwd -P )"
rm -rf $SCRIPTPATH/abi

yarn hardhat compile
yarn hardhat export-abi

cd $SCRIPTPATH/abi 
find . -mindepth 1 -maxdepth 1 ! -name 'src' -exec rm -r {} +
cd $SCRIPTPATH

versions=( v0.8 )
for version in "${versions[@]}"
do
  rm -rf $SCRIPTPATH/abi/$version
  mkdir $SCRIPTPATH/abi/$version
  find $SCRIPTPATH/abi/src/$version -type f -name "*.json" -exec cp {} $SCRIPTPATH/abi/$version/ \;
done

rm -rf $SCRIPTPATH/abi/src

PACKAGE_JSON_PATH=$SCRIPTPATH/package.json
NEW_VERSION=$(jq -r '.version' "$PACKAGE_JSON_PATH")

NEW_TAG=v$NEW_VERSION

git tag -a $NEW_TAG -m "Release version $NEW_VERSION"

git push origin $NEW_TAG