name: manual_check

on: workflow_dispatch

env:
    FOUNDRY_HARDHAT_PROFILE: ci

jobs:
    check-foundry:
        strategy:
            fail-fast: true

        name: Foundry project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install Depends
              run: |
                  forge install
                  yarn install
              id: intsalldepends

            - name: Run Forge build
              run: |
                  forge --version
                  forge build --sizes
              id: build

            - name: Run Forge tests
              run: |
                  forge test -vvv
              id: test

    check-hardhat:
        strategy:
            fail-fast: true

        name: Harthat project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Depends
              run: |
                  yarn install
              id: intsalldepends

            - name: Run hardhat build
              run: |
                  yarn hardhat compile
              id: build

            - name: Run hardhat tests
              run: |
                  yarn hardhat test
              id: test

    check-Solhint:
        strategy:
            fail-fast: true
            matrix:
              solidity-version: [0.8.21]

        name: Solhint Analysis
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              submodules: recursive

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '18'

          - name: Install Solhint
            run: npm install -g solhint

          - name: Run Solhint Analysis
            run: |
              echo "Running Solhint analysis..."
              solhint "**/*.sol"

          - name: Display Completed Message
            run: echo "Solhint analysis completed."